//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personal_Ivanov
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Trade_organizationEntities2 : DbContext
    {
        public static Trade_organizationEntities2 _context;
        public static Trade_organizationEntities2 Context()
        {
            if (_context == null)
            {
                _context = new Trade_organizationEntities2();
            }
            return _context;

        }

        public Trade_organizationEntities2()
            : base("name=Trade_organizationEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ORDER> ORDER { get; set; }
        public virtual DbSet<POSITION> POSITION { get; set; }
        public virtual DbSet<PRODUCT> PRODUCT { get; set; }
        public virtual DbSet<PROVIDER> PROVIDER { get; set; }
        public virtual DbSet<SELLER> SELLER { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TRADE_ORGANIZATION> TRADE_ORGANIZATION { get; set; }
        public virtual DbSet<TRADE_POINT> TRADE_POINT { get; set; }


    }
}
