//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personal_Ivanov
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public int Order_ID { get; set; }
        public System.DateTime Order_date { get; set; }
        public int Trade_point { get; set; }
        public int Provider { get; set; }
        public int Product { get; set; }
        public int Lot { get; set; }
        public decimal Price { get; set; }
    
        public virtual TRADE_POINT TRADE_POINT1 { get; set; }
        public virtual PRODUCT PRODUCT1 { get; set; }
        public virtual PROVIDER PROVIDER1 { get; set; }
    }
}
