//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personal_Ivanov
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRADE_ORGANIZATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRADE_ORGANIZATION()
        {
            this.TRADE_POINT = new HashSet<TRADE_POINT>();
        }
    
        public int Trade_organization_ID { get; set; }
        public string Trade_organization_name { get; set; }
        public string Address { get; set; }
        public string Director { get; set; }
        public int Tax_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRADE_POINT> TRADE_POINT { get; set; }
    }
}
