//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personal_Ivanov
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRADE_POINT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRADE_POINT()
        {
            this.ORDER = new HashSet<ORDER>();
            this.SELLER = new HashSet<SELLER>();
        }
    
        public int Trade_point_ID { get; set; }
        public string Traid_point_name { get; set; }
        public string Type { get; set; }
        public int Trade_organization { get; set; }
        public string Address { get; set; }
        public string Manager { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SELLER> SELLER { get; set; }
        public virtual TRADE_ORGANIZATION TRADE_ORGANIZATION1 { get; set; }
    }
}
